name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:


    
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: TIMEZONE
        run: $timezone = (Invoke-RestMethod -Uri "https://ipinfo.io/json").timezone; switch ($timezone) { "America/Chicago" { $timezone = "Central Standard Time" } "America/Phoenix" { $timezone = "Mountain Standard Time" } "America/Los_Angeles" { $timezone = "Pacific Standard Time" } "America/New_York" { $timezone = "Eastern Standard Time" } "Los Angeles" { $timezone = "Pacific Standard Time" } default { $timezone = "Pacific Standard Time" } }; tzutil /s "$timezone"; Write-Output "Time zone changed to $timezone"

      - name: Time Counter
        run: sleep 21800
